### ISSUE TITLE
add response header 

### ISSUE THREAD

**Issue by kepper** [Edirom/MEIGarage#26]
As the meigarage-repo doesn't allow issues, I put it in here. The client expects a certain header to be set to change the filename of a downloadable file to not be the default "unknown". This surely needs to be fixed somewhere in https://github.com/Edirom/oxgarage/tree/meigarage, though. Here's what the client expects:

https://github.com/Edirom/vife-meigarage-webclient/blob/ed0ce9b7ab6844a9453c93608e60bdd70f01f5c3/src/util.js#L7-L12

**Comment by roewenstrunk** [comment]
Hi Anne, this issue can be closed, the MEIGarage outputs the response header correctly incl. `content-disposition` and `filename` attributes (see https://github.com/Edirom/MEIGarage/blob/2fbef277df1dd99645db36a9f85dc23c6e8b7157/src/main/java/pl/psnc/dl/ege/webapp/servlet/ConversionServlet.java#L464)

**Comment by anneferger** [comment]
Perfect, thanks
