### ISSUE TITLE
Profile Drafter returning HTML instead of ODD

### ISSUE THREAD

**Issue by kepper** [Edirom/MEIGarage#30]
When doing a customization with https://meigarage.edirom.de/profiler, the "Download ODD" button delivers a HTML page, not the generated ODD. It would be wonderful if this could be investigated and ideally fixed prior to this year's MEC workshops (May 19). I am happy to assist after Wednesday next week (May 4). Could you have a look at this by then, @anneferger? Many thanks!

**Comment by anneferger** [comment]
Also Customization to RNG creating empty file (e.g. https://meigarage.edirom.de/ege-webservice/Customization/mei/mei401/c-mei-all/RelaxNG/)

**Comment by anneferger** [comment]
Both issues should now be solved with the current deployment :)

**Comment by kepper** [comment]
I do get a proper ODD file, so this one can be considered fixed, I guess. However, the `Download RNG`-button is still disabled, so that is still open – but might be a separate issue. Many thanks, though 👍

**Comment by anneferger** [comment]
Yes, I added a new issue for that  #31
