### ISSUE TITLE
change download file extensions for customizations

### ISSUE THREAD

**Issue by kepper** [Edirom/MEIGarage#38]
In the [customization service](https://meigarage.edirom.de/customization), when generating any customization, the files to download always use the `.xml` extension. It would be much better, though, if they could use either `.rng` or `.odd`, depending on user selection…

**Comment by anneferger** [comment]
Done in https://meigarage.edirom.de/customization

- [ ] RelaxNG .rng
- [ ] Compiled ODD .odd
