### ISSUE TITLE
customization service returns empty filename

### ISSUE THREAD

**Issue by kepper** [Edirom/MEIGarage#4]
When using the customization service from https://meigarage.edirom.de/customization, RelaxNG output is returned as a file "unknown", so without filename and without file extension. The content of the file seems ok.

**Comment by anneferger** [comment]
See https://github.com/Edirom/mei-customization/blob/b453433669cbb9a1461cfb9ccaccfadb4f5a3b1e/src/main/java/de/edirom/meigarage/mei/MEICustomization.java#L129

**Comment by anneferger** [comment]
I cannot reproduce this, is this still the case @kepper ?

**Comment by anneferger** [comment]
Feel free to reopen if it still happens somewhere
