### ISSUE TITLE
add health check to Dockerfile

### ISSUE THREAD

**Issue by anneferger** [Edirom/MEIGarage#9]
See https://github.com/TEIC/oxgarage/issues/30

**Comment by anneferger** [comment]
In Dockerfile, using Info endpoint

`HEALTHCHECK CMD curl --fail http://localhost/api/healthcheck || exit 1`

**Comment by anneferger** [comment]
`HEALTHCHECK CMD curl --fail http://localhost:8080/ege-webservice/Info || exit 1`

**Comment by anneferger** [comment]
Could be more customized but is working if container is not responding.

@peterstadler close this or add some more checks?

**Comment by peterstadler** [comment]
I think this is good enough for now. If we discover failures that are not caught by this check, we'll improve it later
